-- 코드를 입력하세요

SELECT A.CAR_ID, A.CAR_TYPE, 
ROUND (A.DAILY_FEE * 30 * (100- C.DISCOUNT_RATE) / 100,0) `FEE`
FROM CAR_RENTAL_COMPANY_CAR A
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B ON A.CAR_ID = B.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C ON C.CAR_TYPE = A.CAR_TYPE
WHERE A.CAR_ID NOT IN 
(SELECT CAR_ID 
 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
 WHERE DATE_FORMAT(START_DATE,"%Y-%m-%d") < '2022-11-30'
AND DATE_FORMAT(END_DATE,"%Y-%m-%d") > '2022-11-01') AND A.CAR_TYPE IN ("SUV","세단")
AND C.DURATION_TYPE = "30일 이상"
GROUP BY A.CAR_ID
HAVING `FEE` BETWEEN 500000 AND 2000000
ORDER BY `FEE` DESC, A.CAR_TYPE ASC, A.CAR_ID DESC 


