-- 코드를 작성해주세요
WITH PARENT AS(
    SELECT DISTINCT(PARENT_ITEM_ID)
    FROM ITEM_TREE
    WHERE PARENT_ITEM_ID IS NOT NULL
)
SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID NOT IN(SELECT * FROM PARENT)
ORDER BY ITEM_ID DESC;