-- 코드를 입력하세요
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(B.PRICE * BS.SALES) `TOTAL_SALES`
FROM BOOK B 
JOIN BOOK_SALES BS ON B.BOOK_ID = BS.BOOK_ID
JOIN AUTHOR A ON A.AUTHOR_ID = B.AUTHOR_ID
WHERE DATE_FORMAT(BS.SALES_DATE,"%Y-%m") = "2022-01"
GROUP BY B.CATEGORY, A.AUTHOR_ID
ORDER BY A.AUTHOR_ID ASC, B.CATEGORY DESC
