-- 코드를 입력하세요
WITH J_TOTAL AS(
    SELECT FLAVOR, SUM(TOTAL_ORDER) `TOTAL`
    FROM JULY
    GROUP BY FLAVOR
)

SELECT F.FLAVOR
FROM FIRST_HALF F JOIN J_TOTAL J ON F.FLAVOR = J.FLAVOR
ORDER BY F.TOTAL_ORDER + J.TOTAL DESC
LIMIT 3
