-- 코드를 입력하세요
WITH NO_CANCLE AS(
    SELECT APNT_YMD, APNT_NO, PT_NO, MCDP_CD, MDDR_ID
    FROM APPOINTMENT
    WHERE DATE_FORMAT(APNT_YMD, '%Y-%m-%d') LIKE '2022-04-13' AND 
    MCDP_CD = 'CS' AND APNT_CNCL_YN = 'N'
)

SELECT N.APNT_NO, P.PT_NAME, P.PT_NO, N.MCDP_CD, D.DR_NAME, N.APNT_YMD
FROM NO_CANCLE N
JOIN PATIENT P ON N.PT_NO = P.PT_NO
JOIN DOCTOR D ON D.DR_ID = N.MDDR_ID
ORDER BY N.APNT_YMD