-- 코드를 작성해주세요
WITH FRONT AS(
    SELECT SUM(CODE) AS CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
)
SELECT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D, FRONT F
WHERE D.SKILL_CODE & F.CODE != 0
ORDER BY D.ID ASC