-- 코드를 입력하세요
SELECT AI.ANIMAL_ID AS ANIMAL_ID, AI.NAME AS NAME
FROM ANIMAL_OUTS AO JOIN ANIMAL_INS AI ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE TIMEDIFF(AO.DATETIME, AI.DATETIME) < 0
ORDER BY AI.DATETIME ASC