-- 코드를 작성해주세요
WITH SKILL AS(
    SELECT SUM(CODE) AS CODE
    FROM SKILLCODES
    WHERE NAME IN ('Python', 'C#')
)

SELECT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM SKILL S, DEVELOPERS D
WHERE S.CODE & D.SKILL_CODE != 0
ORDER BY D.ID ASC