-- 코드를 작성해주세요
WITH INFO AS(
    SELECT FISH_TYPE
    FROM FISH_NAME_INFO
    WHERE FISH_NAME IN ('BASS', 'SNAPPER')
)

SELECT COUNT(*) `FISH_COUNT`
FROM FISH_INFO
WHERE FISH_TYPE IN (
    SELECT *
    FROM INFO
)